spring:
  application:
    name: tiles-sanitary-backend

  datasource:
    url: jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:5432/postgres
    username: postgres.recnnsniwonmtoutfyqt
    password: PmwnTXD7FNKat9ZF
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 5

  sql:
    init:
      mode: never

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

  jackson:
    serialization:
      indent-output: true
      write-dates-as-timestamps: false
    default-property-inclusion: non_null

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    root: INFO
    com.inventory: DEBUG